baseurl = "https://toshikis-miscellany.xyz/"
languageCode = "en"
defaultContentLanguage = "en"
title = "俊樹's Miscellaneous"
theme = "dream"

copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.'

googleAnalytics = "UA-206749728-1"

# disqusShortname = ""

enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.goldmark]
  [markup.goldmark.renderer]
     unsafe = true

[params]
  background = "/background/back1.jpg"
  backgroundImage = "/background/back1.jpg"
  linkColor = "seagreen"

  # dark mode
  # defaultDark = true
  backgroundDark = "/background/BackgroundBlack.jpg"
  backgroundImageDark = "/background/BackgroundBlack.jpg"
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404 = true

  author = "安田俊樹"
  description = "Although he prefer mathmatic-related course..."
  avatar = "/avatar/Avatar3.jpg"
  headerTitle = "俊樹's Miscellaneous"
  motto = '<div id="binft"></div><script>var binft=function(t){function r(){return f[Math.floor(Math.random()*f.length)]}function e(){return String.fromCharCode(94*Math.random()+33)}function n(t){for(var n=document.createDocumentFragment(),i=0;t>i;i++){var l=document.createElement("span");l.textContent=e(),l.style.color=r(),n.appendChild(l)}return n}function i(){var r=a[c.skillI];c.step?c.step--:(c.step=o,c.prefixP<l.length?(c.prefixP>=0&&(c.text+=l[c.prefixP]),c.prefixP++):"forward"===c.direction?c.skillP<r.length?(c.text+=r[c.skillP],c.skillP++):c.delay?c.delay--:(c.direction="backward",c.delay=g):c.skillP>0?(c.text=c.text.slice(0,-1),c.skillP--):(c.skillI=(c.skillI+1)%a.length,c.direction="forward")),t.textContent=c.text,t.appendChild(n(c.prefixP<l.length?Math.min(b,b+c.prefixP):Math.min(b,r.length-c.skillP))),setTimeout(i,d)}var l="",a=["Lover of Mathematics and Science."].map(function(t){return t+""}),g=2,o=1,b=5,d=75,f=["rgb(110,64,170)","rgb(150,61,179)","rgb(191,60,175)","rgb(228,65,157)","rgb(254,75,131)","rgb(255,94,99)","rgb(255,120,71)","rgb(251,150,51)","rgb(226,183,47)","rgb(198,214,60)","rgb(175,240,91)","rgb(127,246,88)","rgb(82,246,103)","rgb(48,239,130)","rgb(29,223,163)","rgb(26,199,194)","rgb(35,171,216)","rgb(54,140,225)","rgb(76,110,219)","rgb(96,84,200)"],c={text:"",prefixP:-b,skillI:0,skillP:0,direction:"forward",delay:g,step:o};i()};binft(document.getElementById("binft"));</script>'
  # maxTags = 5
  # categoriesLimitInHeader = 6 # deprecated
  # headerBottomText = "" # deprecated

  # footerBottomText = "Site built and owned by 俊樹Alex."
  rss = true

  # utterancesRepo = ""

  valine = true
  LEANCLOUD_APP_ID = "mmsIvsDj8zvjpXmWqjS1DE0a-MdYXbMMI"
  LEANCLOUD_APP_KEY = "SM2s2HytuJJzA4lKWcAVKGMG"
  placeholder = '说点什么吧...'
  # VALINE_LANGUAGE = ""

  email = "AlexShao20050425@163.com"
  # twitter = ""
  # facebook = ""
  # instagram = ""
  # mastodon = ""
  # linkedin = ""
  # github = "https://github.com/Toshiki0425"
  # stackoverflow = ""
  # codepen = ""
  QQ = "http://wpa.qq.com/msgrd?v=3&uin=1959796501&site=qq&menu=yes"

  favicon = "/favicon/favicon.ico"
  
  siteStartYear = 2020

  highlightjs = true
  highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["clojure", "ocaml"]
  highlightjsTheme = "tomorrow"
  highlightjsThemeDark = "tomorrow-night"

  # search
  enableSearch = true

  # options
  showSummaryCoverInPost = true
  # hasTwitterEmbed = true
  # reversePostAndAside = true
  # shareInAside = true
  fixedNav = true
  # collapsibleTags = true
  # collapseBySummary = true

[params.advanced]
  customCSS = ["css/custom.css"]
  # customJSBefore = []
  customJS = ["/js/custom.js"]

[params.experimental]
  jsDate = true
  jsDateFormat = "yyyy/MM/dd"
  # jsDateFormat = "yyyy年MM月dd日，cccc"

  assetDir = "/assets"